### ISSUE TITLE
[bug] Using it more times can make nginx crash

### ISSUE THREAD

**Issue by anondev-sudo** [j122j/reverseproxy#8]
When you use it like 2 times in a row, it makes nginx to crash.

I tried doing `nginx -s reload` in console more times, and nginx stopped.
I think that the restart commands should be changed to something else, like `systemctl restart nginx`. Tried to use this command 10 times and it has not crashed.

Nginx logs after it crashed 
![image](https://user-images.githubusercontent.com/85408287/141985927-661c1342-b7bd-4053-ab06-9ceb292c2cba.png)

**Comment by j122j** [comment]
It looks like an Nginx bug to crash after a few reload signals. The reason I don't want to use systemctl is that not everyone uses systemctl to manage services. Also if you use `systemctl restart nginx`, it can fail to restart and can't be started again because of a bad config. Reloading also doesn't restart the whole service, it hot reloads the configuration files, so it won't reset existing connections.

**Comment by anondev-sudo** [comment]
So what should I do with it? 


> Also if you use `systemctl restart nginx`, it can fail to restart and can't be started again because of a bad config. Reloading also doesn't restart the whole service, it hot reloads the configuration files, so it won't reset existing connections.


And when you use nginx -s reload, it won't fail to restart?

**Comment by anondev-sudo** [comment]
I have fixed it myself by editing command that will restart nginx in the code to systemctl restart nginx and now it did not crash

**Comment by j122j** [comment]
This looks like a bug in Nginx, the issue will stay closed for now.
